### ISSUE TITLE
Multiple AST processing

### ISSUE THREAD

**Issue by CMatias** [typhonjs-node-escomplex/typhonjs-escomplex-module#1]
Hey,

Escomplex allowed the processing of multiple ast's regarding that an array was given with the format:

```
[ 
    {
         ast: parsedFile,
         path: 'path/to/file'
    },
    ...
]
``` 

It would be nice to retain that functionality, since some of the metrics such as the visibility matrix and such rely on it.

**Comment by typhonrt** [comment]
@CMatias That functionality is still in [escomplex](https://github.com/typhonjs-node-escomplex/escomplex). I moved it out of the escomplex-core due to the processing needing to import `path`. escomplex-core will just do the AST processing and have no outside dependencies.

**Comment by CMatias** [comment]
@typhonrt Yes, but escomplex only allows the path to be supplied and not the ast as well right? That functionality was in the 1.3.0 version of escomplex and was lost in the new 2.0.

**Comment by typhonrt** [comment]
I'm pretty sure it's [still there](https://github.com/typhonjs-node-escomplex/escomplex/blob/master/src/project.js#L21-L37). The tests in [escomplex / project](https://github.com/typhonjs-node-escomplex/escomplex/blob/master/test/project.js#L288-L300) still work. 

I haven't explored that part much yet, but do need to verify that ES modules are supported as the current "project" code still just references CJS / AMD. 

My goal though is to have all the report processing moved to plugins this weekend.

**Comment by CMatias** [comment]
On [index.js](https://github.com/typhonjs-node-escomplex/escomplex/blob/master/src/index.js) of your escomplex you can find the following code:

```
 return typeof source === 'string' ? analyseSource(source, options, parserOptions) : void 0;
``` 

Therefore if anything other than a string indicating a path is provided there will be an error. This is because the syntax trees are being handled by the escomplex parser. There is not an option that allows the program to handle an array of objects with an ast and a path as in [here](https://github.com/escomplex/escomplex/blob/1.3.0/src/index.js).

**Comment by typhonrt** [comment]
@CMatias 

So I added a [one module test](https://github.com/typhonjs-node-escomplex/escomplex/blob/master/test/project.js#L130-L132) and removed the offending line you highlighted above.  Let me know if this fixes the issue. I haven't spent much time on the escomplex / project processing yet. 

Of note you should delete your node_modules directory so that you get the latest from Github for escomplex & escomplex-core. 

Thanks!

**Comment by CMatias** [comment]
@typhonrt 

I created a [pull request](https://github.com/typhonjs-node-escomplex/escomplex/pull/1) which solves the problem. As I stated it is failing on one test. I don't know how to properly handle the case when the source is not valid.

**Comment by typhonrt** [comment]
Hi @CMatias I have finally got the initial project AST processing separated to [typhonjs-escomplex-project](https://github.com/typhonjs-node-escomplex/typhonjs-escomplex-project). I'm going to close this comment as if there are more problems regarding project AST processing please open a new issue on `typhonjs-escomplex-project`. 

I'd definitely like to get your input either way if this solves your needs. I'll be closing your previous PR too as it is outdated after the refactor.

**Comment by typhonrt** [comment]
@CMatias I have thoroughly refined the project AST processing and am nearing API freeze of sorts for all modules of the next-gen typhonjs-escomplex release. [typhonjs-escomplex-project](https://github.com/typhonjs-node-escomplex/typhonjs-escomplex-project) which uses [escomplex-plugin-metrics-project](https://github.com/typhonjs-node-escomplex/escomplex-plugin-metrics-project) plugin provides the project result processing / metrics calculation. 

Many enhancements with strong tests have been added along w/ complete inline documentation. I really refined the dependency resolution that covers source paths + a potential alias for any given file which is used for NPM / JSPM module main entries. In addition the adjacency (dependencies) and visibility (potential reverse indirect dependencies) are compacted / compressed to adjacency / visibility lists which save a lot of space for large projects and directly correlate to data structures useful for working with the reports entries in a project result. The whole module / project processing also is ES Module aware with metrics stored in classes / methods entries of the report(s) / project results.

If you have the time to take a peek I'd be glad to hear any of your thoughts. I'm just finishing up detailed README docs + other high-level architecture docs soon. 

Of note though the modules entries for project AST processing has different keys now:
```
[ 
    {
         ast: <parsed file>,
         srcPath: <full source path as accessed in referenced source code>,
         srcPathAlias: <(optional) alias name such as NPM module name or JSPM alias>,
         filePath: <(optional) path to local source resource> 
    },
    ...
]
```

**Comment by CMatias** [comment]
@typhonrt Hey, I've been busy lately, give me a week or so and I'll take a deeper look into this.
